baseURL: https://adityatelange.github.io/hugo-index/
languageCode: en-us
title: Index
theme: ../../
pygmentsUseClasses: true

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: false
  goldmark:
    renderer:
      unsafe: true

params:
  # showDescriptioninHome: true
  headers:
    key: Title
    value: Tags
    # value: Description

permalinks:
  tags: "@:slug"

taxonomies:
  tag: "tags"

outputs:
  home:
    - HTML
    - RSS
    - JSON # for search
